// global obj that stores all the site's content
// each top-level key is a shelf
const LIBRARY = {
  projects: {
    accentHex: 0x5B9C93, accentCss:'var(--accent-projects)', callPrefix:'PRJ',
    // array of colours for the books
    colors:[0x5B9C93,0x8480B8,0xC98A4B,0x8FAE8B,0x9A6B54,0x4F7C93],
    books:[
      // primary links are highlighted in black
      // slug is a short url-safe ver of the title
      { slug:'shelf-control', title:'Shelf Control', meta:'2026 · Full-stack', description:'A web application that tracks food expiry dates and sends reminders', tags:['JavaScript','CSS','TypeScript','HTML', 'Supabase'], links:[{label:'Live site', url:'shelfctrl.vercel.app', primary:true},{label:'Source code',url:'https://github.com/ejipz/shelf-control', icon:'none'}] },
      { slug:'homebound', title:'Homebound', meta:'2026 · Game', description:'A cozy indie game that finds the fun in the everyday routine of going home', tags:['Python', 'Pygame'], links:[{label:'Source code',url:'https://github.com/ejipz/homebound', icon:'none', primary:true}], related:[{section: 'certificates', title: 'Game Jam 2026 6th Place'}]},
      { slug:'spvr', title:'SharePoint Vulnerability Research Toolkit', meta:'2025 · Tool', description:'A research toolkit for analysing the ToolShell vulnerabilities in Microsoft SharePoint Server 2019 and demonstrating post-exploitation impact in controlled environments', tags:['PowerShell', 'Python'], links:[{label:'Source code',url:'https://github.com/ejipz/research', icon:'none', primary:true}] },
      { slug:'conpanion', title:'Conpanion', meta:'2025 · Prototype', description:'A gamified scam awareness application that educates users through personality quizzes, interactive simulations and the latest scam news', tags:['Figma'], links:[], related:[{section: 'certificates', title: 'BrainHack CODE_EXP 2025'}]},
      { slug:'ev-market-analysis', title:'EV Market Analysis', meta:'2025 · Data Visualisation', description:'A data visualisation project that analyses the global electric vehicle (EV) market to identify the most suitable countries for business expansion and factory setup', tags:['Power BI', 'Power Query'], links:[] },
      { slug:'generositree', title:'Generositree', meta:'2024 · Full-stack', description:'A gamified donation platform that lets users support charitable organisations in Singapore while growing a digital Christmas tree in the spirit of giving', tags:['HTML','JavaScript','CSS','MySQL'], links:[{label:'Source code',url:'https://github.com/Infvrno/BBCS-Dec-Hackathon-Grp27', icon:'none', primary:true}], related:[{section: 'certificates', title: 'BuildingBloCS December Hackathon 2024 4th Place'}] },
      { slug:'hdb-housing-analysis', title:'HDB Housing Analysis', meta:'2024 · Data Analysis', description:'A Jupyter Notebook project that analyses HDB market trends, demographics and dynamics to support data-driven planning and development', tags:['Python', 'pandas', 'Matplotlib', 'Seaborn'], links:[] },
      { slug:'lone-wolf', title:'Lone Wolf Scenario Forensic Report', meta:'2024 · Report', description:'A digital forensics report documenting the forensic analysis of digital evidence recovered from a laptop beloging to Jim Cloudy, a suspect in a planned lone-wolf attack', tags:['Magnet AXIOM', 'Autopsy'], links:[] }
    ]
  },
  certificates: {
    accentHex:0xC98A4B, accentCss:'var(--accent-certs)', callPrefix:'CRT',
    colors:[0xC98A4B,0x9A6B54,0xC9A876,0x8480B8],
    awardColors:[0xD4AF37,0xB8860B,0xCD9B3F,0xE0B972],
    books:[
      // certs
      { type:'cert', slug:'df-pillars', title:'Six Pillars of Digital Forensics', meta:'Magnet Forensics · Jul 2026', description:'', tags:[], links:[{label:'View credential',url:'https://event.on24.com/ceCertficate/83/86/92/68/6/certificate_285846430_b7d18e3e.pdf',primary:true}] },
      { type:'cert', slug:'ai4i', title:'AI4I® – Literacy in AI', meta:'AI Singapore · Jun 2026', description:'', tags:[], links:[{label:'View credential',url:'https://learn.aisingapore.org/certificate-verification/83A175C27A-81360BF6E7-733D49F046/',primary:true}] },
      { type:'cert', slug:'game-jam-26', title:'Game Jam 2026 6th Place', meta:'BuildingBloCS · Jun 2026', description:'Game Jam 2026 was a game development competition held during June Jam 2026 where teams of four were challenged to create a game that finds the magic, humour or challenges in everyday routines or objects.\n\nAs part of the competition, my team developed Homebound. Since none of us had any prior game development experience, we spent much of the competition learning as we built. Despite the steep learning curve, we managed to finish in sixth place, making it a great introduction to game development.', tags:[], links:[], related:[{section: 'projects', title:'Homebound'}] },      
      { type:'cert', slug:'june-jam-26', title:'June Jam 2026', meta:'BuildingBloCS · Jun 2026', description:'June Jam 2026 was a game development workshop organised by BuildingBloCS.\n\n Ironically, even though game development was what got me interested in technology, I realised that even after learning several programming languages, I never actually learnt how to build a game. Wanting to change that, I joined June Jam as an opportunity to explore game development for the first time.\n\n Through the workshop, I learnt how to develop games using Python and was introduced to basic game development concepts. Overall, it was a fun and eye-opening experience that brought me back to where my interest in technology first began.', tags:[], links:[] },      
      { type:'cert', slug:'achievement-teamwork', title:'Certificate of Achievement in Teamwork', meta:'Singapore Polytechnic · Mar 2026', description:'', tags:[], links:[{label:'View credential',url:'https://letters.gov.sg/e9za8-k2nsh-5gyx8-w5rda',primary:true}] },
      { type:'cert', slug:'brainhack-25', title:'BrainHack CODE_EXP 2025', meta:'DSTA · Jun 2025', description:'BrainHack CODE_EXP 2025 was a mobile development hackathon organised by DSTA.\n\n Encouraged by the experience I had during my first hackathon, I decided to take part in another hackathon to learn more about mobile development. Although my team did not end up walking away with anything, I enjoyed learning about how to develop mobile applications using React Native, building a prototype and collaborating with my teammates during our late-night discussions. Looking back, maybe the real treasure was the friends we made along the way after all.', tags:[], links:[{label:'View credential',url:'https://certificates.nextid.com/certificate?id=bc6211e7-350d-431b-acb6-b66aef4b88fe',primary:true}], related:[{section: 'projects', title: 'Conpanion'}] },
      { type:'cert', slug:'pcep', title:'Certified Entry-Level Python Programmer (PCEP)', meta:'Python Institute® · Jun 2025', description:'PCEP certifies that an individual is familiar with universal computer programming concepts like data types as well as the Python programming language syntax, semantics and runtime environment.\n\nI completed this certification while working on my Final Year Project at Singapore Polytechnic as our solution was built using Python and I wanted to refresh and improve my Python skills so I could contribute more effectively to the project and support my team.', tags:[], links:[{label:'View credential',url:'https://www.credly.com/badges/81cd6fe6-4b3a-42d6-b112-825d95a4c978/public_url',primary:true}] },
      { type:'cert', slug:'fst', title:'Fundamentals of Sustainability and Technology', meta:'IBM · Apr 2025', description:'', tags:[], links:[{label:'View credential',url:'https://www.credly.com/badges/6546eaf8-7fdb-4475-a33d-010f458f7767/public_url',primary:true}] },
      { type:'cert', slug:'dw', title:'Working in a Digital World: Professional Skills', meta:'IBM · Apr 2025', description:'', tags:[], links:[{label:'View credential',url:'https://www.credly.com/badges/828335f0-3b79-4df6-9730-2a5e98bbec45/public_url',primary:true}] },
      { type:'cert', slug:'agile-explorer', title:'Agile Explorer', meta:'IBM · Apr 2025', description:'', tags:[], links:[{label:'View credential',url:'https://www.credly.com/badges/ccce6e07-153b-4422-a75c-64f83016cddb/public_url',primary:true}] },
      { type:'cert', slug:'pm-fundamentals', title:'Project Management Fundamentals', meta:'IBM · Apr 2025', description:'', tags:[], links:[{label:'View credential',url:'https://www.credly.com/badges/df2cb6fd-a933-417b-9ad0-63ee24978764/public_url',primary:true}] },
      { type:'cert', slug:'data-analytics', title:'Certificate in Data & Analytics', meta:'Singapore Polytechnic · Mar 2025', description:'', tags:[], links:[{label:'View credential',url:'https://letters.gov.sg/bbqf3-e1okz-y3zzp-bl9xh',primary:true}] },
      { type:'cert', slug:'dec-conference-24', title:'December Conference 2024', meta:'BuildingBloCS · Dec 2024', description:'', tags:[], links:[] },      
      { type:'cert', slug:'dec-hackathon-24', title:'BuildingBloCS December Hackathon 2024 4th Place', meta:'BuildingBloCS · Dec 2024', description:'BuildingBloCS December Hackathon 2024 was a week-long web development hackathon where participants were challenged to build a platform that encourages people to contribute to the greater good of society during the Christmas season. The hackathon centered around the themes of generosity, community and festivity.\n\nWanting to apply the web development skills I learnt at Singapore Polytechnic (SP), I joined the hackathon and was randomly teamed up with three other SP students. Since it was my first hackathon, I approached it as an opportunity to learn, gain experience and work with others in a fast-paced environment. Our project ended up being awarded third runner-up at the end of the hackathon, which was an encouraging outcome for my first hackathon.', tags:[], links:[], related:[{section: 'projects', title: 'Generositree'}] },      
      { type:'cert', slug:'completion', title:'Certificate of Completion', meta:'National Youth Council Singapore · Dec 2024', description:'', tags:[], links:[{label:'View credential',url:'https://letters.gov.sg/0dgux-t7da0-ms31b-y3odp',primary:true}] },      
      { type:'cert', slug:'achievement-peer', title:'Certificate of Achievement in Peer Support', meta:'Health Promotion Board · Sep 2024', description:'', tags:[], links:[] },      
      { type:'cert', slug:'pandas', title:'Data Manipulation with pandas', meta:'DataCamp · Jul 2024', description:'', tags:[], links:[{label:'View credential',url:'https://www.datacamp.com/completed/statement-of-accomplishment/course/3bc451a14e408cf763329924479a2a3b03a57cb7',primary:true}] },
      { type:'cert', slug:'stti', title:'Speech-to-Text Interpreting (STTI) Training Programme', meta:'Equal Dreams · Jun 2024', description:'Speech-to-text interpreting involves transcribing spoken information into text, providing a meaning for meaning translation. This service is used in both online and in-person learning environments by Deaf and Hard of Hearing individuals who prefer to access information through text, either as a primary method or alongside sign language interpretation.\n\n I wanted to learn a new skill and contribute to improving access for Deaf and Hard of Hearing individuals so I joined a training program offered by the SP EDGE programme. The month-long course ended with a practical assessment. Initially, I struggled with the speed required for accurate transription as I do not consider myself a fast typer. However, with practice and the guidance of the trainers, I managed to pass the assessment and was offered a place in their mentorship programme, which is available to students who demonstrate competency in speech-to-text interpreting.', tags:[], links:[] },
      { type:'cert', slug:'intermediate-python', title:'Intermediate Python', meta:'DataCamp · May 2024', description:'', tags:[], links:[{label:'View credential',url:'https://www.datacamp.com/completed/statement-of-accomplishment/course/ca89812c25eb9ffc52c72f79612537c3e07e621c',primary:true}] },
      { type:'cert', slug:'data-literacy', title:'Data Literacy', meta:'DataCamp · May 2024', description:'', tags:[], links:[{label:'View credential',url:'https://www.datacamp.com/skill-verification/DL0030210991962',primary:true}] },
      { type:'cert', slug:'introduction-python', title:'Introduction to Python', meta:'DataCamp · Apr 2024', description:'', tags:[], links:[{label:'View credential',url:'https://www.datacamp.com/completed/statement-of-accomplishment/course/dc403530029231c68f71a9be55c296b61e47e578',primary:true}] },
      { type:'cert', slug:'ossa', title:'Organizational Systems Security Analyst™ (OSSA)', meta:'ThinkSECURE Pte Ltd · Apr 2024', description:'During my Year 1 Semester 2 break in Singapore Polytechnic, I completed a 5-day course called Organisational Systems Security Analyst. The course included a multiple-choice and practical test on the final day, combining theory with hands-on questions that required interaction with lab machines through their VPN network.\n\n During this course, I encountered a new marking scheme where incorrect answers led to point deductions. Despite this challenge, I successfully passed the examination and earned the certificate.', tags:[], links:[] },
      { type:'cert', slug:'seed-cp', title:'SEED Code League 2023', meta:'SP School of Computing · Nov 2023', description:'Code League was a competitive programming competition held by a student interest group called SEED in Singapore Polytechnic. Although I have been programming since 2021, it was my first time participating in such competitions. We had to form teams so I entered the competition with my friend as a group of 2. Since I had no prior experience, I did not know what to expect and found some of the challenges challenging. However, I learnt a lot through this competition and it was definitely a great eye-opener to the world of competitive programming.', tags:[], links:[] },      
      { type:'cert', slug:'cyber-defenders-challenge', title:'Cyber Defenders Challenge (High Distinction)', meta:'Grok Academy · Jan 2022', description:'', tags:[], links:[] },

      // awards
      { type:'award', slug:'csit-prize', title:'CSIT Prize', meta:'Singapore Polytechnic · Apr 2026', description:'Awarded for excellent overall academic performance.', tags:[], links:[] },
      { type:'award', slug:'emb', title:'Edusave Certificate of Academic Achievement 2025', meta:'Ministry of Education · Sep 2025', description:'Awarded to students who are within the top 25% of their institution’s level and course in terms of academic performance and have demonstrated good conduct.', tags:[], links:[] },
      { type:'award', slug:'esa', title:'Edusave Skills Award 2025', meta:'Ministry of Education · Sep 2025', description:'Awarded to up to 5% of students in the penultimate year from each course who have demonstrated excellent professional and soft skills throughout their course of study, and good conduct.', tags:[], links:[] },
      { type:'award', slug:'dhr', title:'Director\'s Honour Roll', meta:'Singapore Polytechnic · Jun 2025', description:'The Director’s Honour Roll is generally awarded to not more than the top 10% of students of each cohort.', tags:[], links:[] },
      { type:'award', slug:'emb', title:'Edusave Certificate of Academic Achievement 2024', meta:'Ministry of Education · Sep 2024', description:'Awarded to students who are within the top 25% of their institution’s level and course in terms of academic performance and have demonstrated good conduct.', tags:[], links:[] },
      { type:'award', slug:'dhr2', title:'Director\'s Honour Roll', meta:'Singapore Polytechnic · Ju1 2024', description:'The Director’s Honour Roll is generally awarded to not more than the top 10% of students of each cohort.', tags:[], links:[] },
      { type:'award', slug:'csit-ds', title:'CSIT Diploma Scholarship', meta:'Centre for Strategic Infocomm Technologies (CSIT) · Dec 2023', image:'assets/images/scholarship.jpg', description:'Centre for Strategic Infocomm Technologies (CSIT) is a technical agency under the Ministry of Defence that develops cutting-edge digital technologies to meet Singapore\'s security needs.\n\n I had the honour of receiving this scholarship during my first year at Singapore Polytechnic with a Year 2 senior from Diploma in Information Technology. I am grateful for the support and recognition this scholarship has provided and will continue striving to develop myself holistically.', tags:[], links:[] },
      { type:'award', slug:'excellence-award-national', title:'Excellence Award (National Examination)', meta:'Bukit View Secondary School · Apr 2023', description:'', tags:[], links:[] },
      { type:'award', slug:'sac', title:'School Advisory Committee Outstanding Performance Award (National Examination)', meta:'Bukit View Secondary School · Apr 2023', description:'', tags:[], links:[] },
      { type:'award', slug:'psl', title:'Peer Support Leader Certificate of Appreciation', meta:'Bukit View Secondary School · Apr 2022', description:'Awarded in recognition of the student\'s valuable contributions as a Peer Support Leader', tags:[], links:[] },
      { type:'award', slug:'excellence-award-class', title:'Excellence Award (Class) 2021', meta:'Bukit View Secondary School · Jan 2022', description:'Awarded to the top student of each class.', tags:[], links:[] },
      { type:'award', slug:'es-22', title:'Edusave Scholarship 2022', meta:'Ministry of Education · Jan 2022', description:'Students who are within the top 10% of their school’s level and course in terms of academic performance, and have demonstrated good conduct.', tags:[], links:[] },
      { type:'award', slug:'es-21', title:'Edusave Scholarship 2021', meta:'Ministry of Education · Jan 2021', description:'Students who are within the top 10% of their school’s level and course in terms of academic performance, and have demonstrated good conduct.', tags:[], links:[] },
    ]
  },
  experience: {
    accentHex:0x8480B8, accentCss:'var(--accent-exp)', callPrefix:'EXP',
    colors:[0x8480B8,0x5B9C93,0x9A6B54,0x4F7C93],
    books:[
      { slug:'vuln-research', title:'Cyber Vulnerability Researcher', meta:'Centre for Strategic Infocomm Technologies · Sep 2025 – Feb 2026', description:'', bullets:['Researched on SharePoint security vulnerabilities','Analysed the root causes of SharePoint vulnerabilities','Developed proof of concepts to demonstrate real world exploitability', 'Performed re-verification of SharePoint vulnerabilities', 'Looked into security mitigations'], links:[] },
      { slug:'warehouse', title:'Warehouse Assistant', meta:'LF Logistics · Feb 2023 – Mar 2023', description:'', bullets:['Efficiently picked, packed and accurately scanned items','Organised and sorted goods', 'Ensured proper labeling and thorough quality checks of health supplements and e-commerce consumer products', 'Made use of advanced barcode scanning techniques such as RDT scanners to scan pallets'], links:[] },
      { slug:'retail', title:'Retail Associate', meta:'NTUC FairPrice · Jan 2023', description:'', bullets:['Assisted in the restocking of items in the supermarket', 'Packed fresh foods such as fruits and vegetables into the packages', 'Performed stocktaking and checking of expiring items', 'Answered queries from the customers', 'Aided in managing and resolving conflicts between the sales team and customers, achieving mutually beneficial outcomes'], links:[] }
    ]
  },
  about: {
    accentHex:0x8FAE8B, accentCss:'var(--accent-about)', callPrefix:'ABT',
    colors:[0x8FAE8B,0xC98A4B,0x5B9C93],
    books:[
      { slug:'about-me', title:'About Me', meta:'Biography', description:'Hi! I am Lee Jia Hui, a Diploma in Infocomm Security Management graduate with some knowledge in cybersecurity and programming languages such as Python, JavaScript and C. I enjoy coding new projects and learning about cybersecurity-related topics in my free time and I aspire to be a Digital Forensics Examiner in the near future.', tags:[], links:[] },
      { slug:'edu', title:'Education', meta:'', description:'', schools:[
                // schools is an array of structured objs
                { logo:'assets/logos/sp.png', name:'Singapore Polytechnic', program:'Diploma in Infocomm Security Management (with Merit)', years:'2023 – 2026' }, 
                { logo:'assets/logos/bvss.png', name:'Bukit View Secondary School', program:'General Certificate of Education Ordinary Level', years:'2019 – 2022' }
              ], tags:[], links:[] 
      },
      { slug:'skills', title:'Skills', meta:'', description:'', bullets:['Python', 'Full-stack Web Development', 'Data Science', 'Digital Forensics', 'JavaScript', 'Cyber Defence', 'Network Security', 'Vulnerability Scanning', 'Microsoft Excel', 'PowerBI'], links:[] },
      { slug:'fav-reads', title:'Favourite Reads', meta:'Just for fun', description:'<strong>Last Read:</strong> All the Lovers in the Night by Mieko Kawakami\n\n <strong>All-time Favourites:</strong>', bullets:['If You Could See the Sun by Ann Liang','Almond by Sohn Won-pyung','Tuesdays with Morrie by Mitch Albom'], tags:[], links:[] },

      // links have no label to render as icon-only
      { slug:'contact', title:'Get In Touch', meta:'Contact', description:'Feel free to reach out anytime', tags:[], links:[{label:'',url:'mailto:cappujinno.o@gmail.com',primary:true},{label:'',url:'https://www.linkedin.com/in/lee-jiah/', icon: 'linkedin'},{label:'',url:'https://github.com/ejipz', icon:'github'}] }    ]
  }
};